config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root "courses#index"
get 'courses/new' , to: 'courses#new'
  get "about" , to: "pages#about"
resources :students, except: [:destroy]
get "login", to: 'logins#new'
post "login", to: 'logins#create'
get 'logout', to: 'logins#destroy'
#get 'course_enroll', to: 'student_courses#new'
post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
validates :name, presence: true, length: { minimum: 5, maximum: 50 }
validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
validates :description, presence: true, length: { minimum: 10, maximum: 300 }
has_many :student_courses
has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                          uniqueness: { case_sensitive: false },
                          format: { with: VALID_EMAIL_REGEX }
has_secure_password
has_many :student_courses
has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :require_user
  def current_user
  @current_user ||= Student.find(session[:student_id]) if session[:student_id]
end
  def logged_in?
    !!current_user
  end
def require_user
  if !logged_in?
    flash[:notice] = "you must be logged in to perform that action"
    redirect_to login_path
  end
end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user
def index

  @courses = Course.all
end
def new
end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]

  def new
  end
  def create
    student = Student.find_by(email: params[:logins][:email].downcase)
    if student && student.authenticate(params[:logins][:password])
      session[:student_id] = student.id
flash[:notice] = "you have successfully login"
redirect_to student
    else
flash.now[:notice] = "Something was wrong with login information"
render "new"
    end
  end
  def destroy
    session[:student_id] = nil
    flash[:notice] = "you have successfully logout"
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user
  def about
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

def create
  course_to_add = Course.find(params[:course_id])
  unless current_user.courses.include?(course_to_add)
StudentCourse.create(course: course_to_add,student: current_user)
flash[:notice] = "you have successfully enrollement to #{course_to_add.name}"
redirect_to current_user
  else
    flash[:notice] = "something went wrong with your enrollement"
#  binding.break
redirect_to root_path
end
end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update]
  skip_before_action :require_user, only: [:new, :create]
  before_action :require_same_student, only: [:edit, :update]
def index
  @students = Student.all
end
def new
  @student = Student.new
end
def show

end
def create
  @student = Student.new(student_params)
  if @student.save
flash[:notice] = "you have successfully signed up"
redirect_to @student
  else
       #binding.break
  render :new, status: :unprocessable_entity
end
end
def edit

end
def update

        if @student.update(student_params)
flash[:notice] = "you have successfully update your profile"
redirect_to @student
        else
          render :edit, status: :unprocessable_entity
end
end
private
def student_params
params.require(:student).permit(:name, :email, :password, :password_confirmation)
end
def set_student
    @student = Student.find(params[:id])
end
def require_same_student
  if current_user != @student
    flash[:notice] = "you can only edit your own profile"
    redirect_to student_path(current_user)
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
  if logged_in?
link_to("logout", logout_path, method: :delete)
 else
link_to("login", login_path)
 end
end
end

app/views/courses/index.html.erb
<div class="row">
      <div class="col s12">
<h3 class="center-align">courses listining</h3></div>
</div>
<div class="row">
  <% @courses.each do |course| %>
        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
            <p><%= course.description %></p>
          </div>
          <div class="card-action">
            <% if logged_in? && !(current_user.courses.include?(course)) %>
              <%= button_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
              <% end %>
            <a href="#">Info</a>
          </div>
        </div>
      </div>
  <% end %>
</div>
<div class="row">
      <div class="col s1">1</div>
      <div class="col s1">2</div>
      <div class="col s1">3</div>
      <div class="col s1">4</div>
      <div class="col s1">5</div>
      <div class="col s1">6</div>
      <div class="col s1">7</div>
      <div class="col s1">8</div>
      <div class="col s1">9</div>
      <div class="col s1">10</div>
      <div class="col s1">11</div>
      <div class="col s1">12</div>
    </div>

app/views/courses/new.html.erb
<h1>new</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development and training.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>

        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2024 Tech University
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
    <header>
      <ul id="dropdown1" class="dropdown-content">
<li><%= session_link %></li>
<% if logged_in? %>
  <li><%= link_to "profile" , student_path(current_user) %></li>
  <% end %>
  <li class="divider"></li>
  <li><a href="#!">three</a></li>
</ul>
<ul id="dropdown2" class="dropdown-content">
<li><%= session_link %></li>
<% if logged_in? %>
  <li><%= link_to "profile" , student_path(current_user) %></li>
  <% end %>
<li class="divider"></li>
<li><a href="#!">three</a></li>
</ul>
    <nav>
      <div class="container">
      <div class="nav-wrapper">
        <%= link_to "Tech University", root_path, class: "brand-logo" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Courses", root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Students", students_path %></li>
          <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <li><%= link_to "Courses", root_path %></li>
          <li><a href="#">Enrollement</a></li>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
      </div>
    </nav>
    <div class="container">


    <div id="error_explanation" class="white-text text-darken-2">
  <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2" id="fade-out-target">


  <% flash.each do |name, msg| %>

          <%= msg %>

  <% end %>
</div>
</div>
</div>
    </div>

    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= javascript_importmap_tags %>

  </head>
  <body>
<%= render 'layouts/navigation' %>
    <main>
    <div class="container">
          <%= yield %>
    </div>
</main>
    <%= render 'layouts/footer' %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

                                    <!--JavaScript at end of body for optimized loading-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <!-- Materialize JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

<script>
  // Get the element with the ID "fade-out-target"
 var element = document.getElementById('fade-out-target');
  // Define a function to fade out the element
  function fadeOut() {
    // Reduce the opacity of the element gradually
    var opacity = 1;
    var intervalId = setInterval(function() {
      if (opacity > 0) {
        opacity -= 0.1; // Decrease opacity by 0.1
        element.style.opacity = opacity;
      } else {
        clearInterval(intervalId); // Stop the fading animation
        element.style.display = 'none'; // Hide the element when fading is complete
      }
    }, 100); // Run the fading animation every 100 milliseconds
  }
// Initialize dropdown
document.addEventListener('DOMContentLoaded', function() {
var elems = document.querySelectorAll('.dropdown-trigger');
var instances = M.Dropdown.init(elems);

});
// Initialize collapsible (sidenav) for mobile
 document.addEventListener('DOMContentLoaded', function() {
   var elems = document.querySelectorAll('.sidenav');
   var instances = M.Sidenav.init(elems);
 });




// Call the fadeOut function after a delay of 1000 milliseconds (1 second)
setTimeout(fadeOut, 4000);
</script>
</body>
</html>

app/views/logins/new.html.erb
<div class="container">
  <div class="sign-up-form">

  <div class="card-panel">
    <div class="col s12 m12 l12">


<h3 class="header"> <center>Login</center></h3>

    <div class="row">
      <%= form_for :logins, html: { class: "col s12" } do |f| %>


        <div class="row">
          <div class="input-field col s12">
            <%= f.email_field :email, id: "email" %>
            <%= f.label :email %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.password_field :password, id: "password" %>
            <%= f.label :password %>
          </div>
        </div>


        <div class="row">
       <div class="col s12 center-align">
         <button class="btn waves-effect waves-light" type="submit" name="action">login
           <i class="material-icons right">send</i>
         </button>
       </div>
     </div>
      <% end %>
      </div>
</div>
  </div>
</div>
</div>

app/views/pages/about.html.erb
<h1>about pages</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation" class="red-text text-darken-2">

      <div class="card-panel">
        <div class="col s12 m12 l12">
    <h5><%= pluralize(obj.errors.count, "error") %> prohibited this model from being saved:</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>
<div class="container">
  <div class="sign-up-form">

  <div class="card-panel">
    <div class="col s12 m12 l12">


<h3 class="header"> <center><%= @student.new_record? ? "Sign up" : "edit" %></center></h3>

    <div class="row">
      <%= form_for @student, html: { class: "col s12" } do |f| %>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :name, id: "name" %>
            <%= f.label :name %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.email_field :email, id: "email" %>
            <%= f.label :email %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.password_field :password, id: "password" %>
            <%= f.label :password %>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.password_field :password_confirmation, id: "email" %>
            <%= f.label :password_confirmation %>
          </div>
        </div>

        <div class="row">
       <div class="col s12 center-align">
         <button class="btn waves-effect waves-light" type="submit" name="action"><%= @student.new_record? ? "Sign Up!" : "edit" %>
           <i class="material-icons right">send</i>
         </button>
       </div>
     </div>
      <% end %>
      </div>
</div>
  </div>
</div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
      <div class="col s12">
<h3 class="center-align">Students Directory</h3></div>
</div>
<div class="row">
  <% @students.each do |student| %>
        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Name: <%= student.name %></span>
            <p> Email: <%= student.email %></p>
            <p>course enrollement</p>
          </div>
          <div class="card-action">
            <%= link_to "View profile", student_path(student) %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<ul>
  <li>this is : courses</li>
</ul>
<ul>
  <li>this is : courses</li>
</ul>
<ul>
  <li>this is : courses</li>
</ul>
<div class="row">
      <div class="col s1">1</div>
      <div class="col s1">2</div>
      <div class="col s1">3</div>
      <div class="col s1">4</div>
      <div class="col s1">5</div>
      <div class="col s1">6</div>
      <div class="col s1">7</div>
      <div class="col s1">8</div>
      <div class="col s1">9</div>
      <div class="col s1">10</div>
      <div class="col s1">11</div>
      <div class="col s1">12</div>
    </div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row sign-up-form">

        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Name: <%= @student.name %></span>
            <p> Email: <%= @student.email %></p>
            <p>course enrollement <% if @student.courses.empty? %>
              None
                  <% else %>
              <ul>
                <% @student.courses.each do |course| %>
                <li><%= course.name %></li>
                  <% end %>
              </ul>
<% end %>
             </p>
          </div>

        </div>
        <% if current_user == @student %>
        <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student),class:"waves-effect waves-light btn" %>
        <% end %>
      </div>

</div>